### PR TITLE
Few fixes on Windows documentation.

### PR DESCRIPTION
**Pull request by darktears**
- Make sure to tell users to use MSVS 2015 starting with Crosswalk 21
- Make sure to correctly tell to use target_arch=x64 in their GYP_DEFINES

### CODE REVIEW

**Comment by darktears** [comment]
@halton someone needs to make the same changes on the chinese version, merge this and deploy this.

**Comment by halton** [comment]
LGTM and merging.

@lisa0314 please upload the related changes for Chinese version.

**Comment by darktears** [comment]
@halton @lisa0314 the changes are not published on the english version. See https://crosswalk-project.org/documentation/windows/build_crosswalk_for_windows.html .

**Comment by halton** [comment]
@darktears Yes, we're waiting for @baleboy 's back. No one has permission to publish yet.

**Pull request merged**
