### PR TITLE
Refine manifest translation for chinese

### PR DESCRIPTION
**Pull request by chuan9**
BUG=XWALK-7016

### CODE REVIEW

**Comment by chuan9** [comment]
@jondong @lisa0314 I have a look at manifest translation and fount it's difficult to read, so refine the translation. Please have a review. Thanks

**Comment by baleboy** [comment]
I'd like to have a LGTM from somebody who reads Chinese before merging this.

**Comment by chuan9** [comment]
@jondong @lisa0314 Please have review. Thanks!

**Comment by jondong** [comment]
LGTM, nice translation @chuan9 ! Thanks for the PR

**Pull request merged**
