### PR TITLE
Windows: python xwalk\gyp_xwalk to generate VS solution & project

### PR DESCRIPTION
**Pull request by astojilj**
@darktears @bspencer please review, thanks.

### CODE REVIEW

**Comment by rakuco** [comment]
makes sense, I only wonder if we shouldn't merge this part of the documentation with what we already have in "Contribute -> Building Crosswalk" (as well as remove the Tizen part of the latter).

**Comment by astojilj** [comment]
@rakuco windows and android are quite different, chromium projects tend to keep it apart. I like that @darktears split it. Maybe refactor content in "Contribute -> Building Crosswalk" to common (MAC, Linux) and Android pages.

**Comment by darktears** [comment]
You do not need this because gclient sync already ran python xwalk\gyp_xwalk

**Comment by astojilj** [comment]
it didn't generate it for me; don't remember, but maybe didn't add msvs to GYP_GENERATORS before gclient sync.

**Pull request merged**
