### PR TITLE
Structure change for Chinese version

### PR DESCRIPTION
**Pull request by lisa0314**
1. The configuration about the choices of the layout templates is in the
_data.json in each directory by adding some language property.
2. the _layout templates for Chinese and English Version are separated.
3. there exist different files about navigation column for different
languages.
4. all files for Chinese Version are suffixed with "_zh".

### CODE REVIEW

**Comment by lisa0314** [comment]
@bspencer , I have re-submit the PR again. 
1. " Sites without '.html' come up 404": As you said, any website that does not have '.html' on the end comes as "not found". As a solution, I check the url before the redirection and add the '.html' as suffix if needed.
2. "No Chinese page, fail to English 404": We only use the current value of cookie to decide the redirection before, so when you click a Chinese page that not exits, the English 404 page will show if you are under English version. Now, we solve this problem by adding the current value of url as a flag to decide the redirection.

**Comment by lisa0314** [comment]
@bspencer , Please help to review, thanks.
I'm really sorry for the issue of the menu item not consistent at small window sizes. I am not so familiar with css, so I have not solved this issue even though I have spent a lot of time. I hope all elements in the navigation bar are consistent with each other, having the same style. So would you please to help me with this issue? If you are willing to offer some help , it will be of great benefit for this issue.

**Comment by bspencer** [comment]
Lisha, I'll take a look at the UI.  I agree it is sometimes tricky to get it right.

**Comment by lisa0314** [comment]
@bspencer , Thanks for your help.
As you said, we could show a banner at the top of the English version page that said something instead of showing the 404 page for not-found. I have submited a new patch to solve this issue.
I added a file "bar.ejs' in the folder of "public/_includes" and set it invisible. Before switching to  Chinese version, it firstly checkout if there exits the corresponding Chinese translation page by sent a http-request. If there doesn't exist translation page, the hidden "bar.ejs" will show up.

**Pull request merged**
