### PR TITLE
Add wechat official accounts QRcode for chinese website

### PR DESCRIPTION
**Pull request by chuan9**
BUG=XWALK-6946

### CODE REVIEW

**Comment by jondong** [comment]
LGTM, thanks for the PR. @bspencer would you please take a look? Thanks

**Comment by baleboy** [comment]
could the weibo and wechat items be next to each other rather than one on top of the other? There is a lot of empty space on the right of the page now.

**Comment by chuan9** [comment]
@baleboy Of course. Put the WeChat Qrcode in first position since we focus our effort on this channel. Thanks!

**Comment by baleboy** [comment]
Thanks

**Pull request merged**
