### PR TITLE
For Windows; export GYP_GENERATORS='ninja' to set GYP_GENERATORS=ninja

### PR DESCRIPTION
**Pull request by astojilj**
Instructions fix for Windows

### CODE REVIEW

**Comment by r0b5t4** [comment]
I think it would be better to have paragraphs like below, for clarity:

Android, Linux:
> export ..
>  python ...

Windows:
> set ...
> python ...

**Comment by darktears** [comment]
@astojilj one should really add it in the environment dialog on Windows.

**Comment by darktears** [comment]
but agree the fix is good anyway. In the other hand i think @bspencer is revamping the windows part.

**Comment by rakuco** [comment]
fwiw, `SETX foo bar` does the same without the GUI. isn't it enough to mention that if one wants this change to stick it needs to be done with the dialog or `SETX`?

**Comment by rakuco** [comment]
@astojilj: fyi, in general, we do not put subsequent commits that address review points as part of the pull request and just squash them into the original one, otherwise we end up with commits in the history that do not make much sense on their own.

**Comment by astojilj** [comment]
@darktears  - good point about env settings dialog, but after @rakuco 's comment about SETX, not sure what to add there. Now that @bspencer is aware of this, we can discard this.


@rakuco - "we do not put subsequent commits that address review points as part of the pull request and just squash them into the original one".
amend + force push is preferred? Or, keep commit sequence with the same commit message, or to squash them later?
Anyway, good to cover here: https://crosswalk-project.org/contribute/contributing-code.html

**Comment by rakuco** [comment]
> amend + force push is preferred? Or, keep commit sequence with the same commit message, or to squash them later?

Either squash + force push if you already have more than one commit, or just amend + force push if you have not created a new commit yet. As long as we get to see one or more logically separated commits, it's fine.

> Anyway, good to cover here: https://crosswalk-project.org/contribute/contributing-code.html

Makes sense. We already have a `CONTRIBUTING.md` that is shown automatically to people when they submit a pull request, but only in a few repositories like [Crosswalk's itself](https://github.com/crosswalk-project/crosswalk/blob/master/CONTRIBUTING.md).

**Comment by astojilj** [comment]
@darktears almost set it myself to system env, but then remembered I set it to different value in Skia: set GYP_GENERATORS=ninja,msvs-ninja in order to generate VS solution and build/debug in VS, maybe better to leave it as it is. What do you think?

**Comment by astojilj** [comment]
@rakuco thanks. 1 commit.

**Comment by darktears** [comment]
That's basically covered here : https://docs.google.com/document/d/1WYWMXvdySJrmU7t8RIw6FueyXNVeSuKbQ9TnFJlUPbM/edit#heading=h.ahuuwmd06u79

which is going live soon.

**Pull request merged**
