### PR TITLE
Update documentation for the sample of using Crosswalk with Android S…

### PR DESCRIPTION
**Pull request by fujunwei**
…tudio

BUG=XWALK-5744

### CODE REVIEW

**Comment by fujunwei** [comment]
@bspencer PTAL, thanks.

**Comment by rakuco** [comment]
Why is the Maven example still packaged as a tarball instead of being added as a sample to crosswalk-samples?

**Comment by fujunwei** [comment]
Ok, It will be added to crosswalk-samples.

**Comment by rakuco** [comment]
This shouldn't have been merged as-is, there should be no tarball whatsoever. I'll reopen XWALK-5744.

**Pull request merged**
