### PR TITLE
[Android] Enable proguard for crosswalk to compress apk size

### PR DESCRIPTION
**Pull request by heke123**
Add description about including proguard config file in webpage of
embedding crosswalk.
BUG=XWALK-3854

### CODE REVIEW

**Comment by heke123** [comment]
@halton @baleboy @bspencer   PR submitted, could you please help give a review? thanks.

**Comment by bspencer** [comment]
Thanks for the PR

**Comment by suleymanccelik** [comment]
I added --enable-proguard command to xwalk-command-line file under asset directory in my android application but compression is not successful.
I am using embedded crosswalk version stable 16.45.421.19.
Content of xwalk-command-line file : xwalk --enable-proguard --enable-lzma --allow-running-insecure-content --disable-pull-to-refresh-effect --disk-cache-size=0

**Comment by heke123** [comment]
The proguard function might be broken by java reflections if those reflections referenced class/function/member names are not added into the proguard rule.  I'll look into this issue.

**Comment by suleymanccelik** [comment]
@heke123 thanks for reply. How can I follow progress of that issue?

**Comment by heke123** [comment]
@suleymanccelik  I'll start as soon as I finish some high priority bugs in hand, and update to you then. By the way, the "--enable-proguard" is used for shrink size(~150K reduced), not for obfuscation purpose.

**Comment by heke123** [comment]
@suleymanccelik  Sorry,you are using "xwalk-command-line-file" instead of "xwalk-command-line".  I'm afraid the "--enable-proguard --enable-lzma" cannot used in "command-line-file". Because they are flags for actions happen during packaging apk. they are not flags set for chromium core in runtime.
So you can only use them with make_apk.py.

**Comment by suleymanccelik** [comment]
"--enable-proguard" command is added to following url https://github.com/crosswalk-project/crosswalk-website/wiki/Crosswalk-Command-Line-Options#xwalk-command-line-options . The documentation leds me to misunderstanding about xwalk-command-line. Sorry for misunderstanding. Do I have to use make_apk.py to use --enable-proguard and --enable-lzma? @heke123

**Comment by heke123** [comment]
yes,  --enable-proguard and --enable-lzma are only for make_apk.py.

**Comment by suleymanccelik** [comment]
Okay @heke123. Thanks for replies.

**Comment by heke123** [comment]
@suleymanccelik, below is the crosswalk-lite wiki if you care about the apk size.  
https://github.com/crosswalk-project/crosswalk-website/wiki/Crosswalk-Project-Lite

**Pull request merged**
