### PR TITLE
[Lite] Update release URL according XWALK-3347

### PR DESCRIPTION
**Pull request by halton**

### CODE REVIEW

**Comment by halton** [comment]
@baleboy  @bspencer 

Please hold on merging before @rakuco does the change on 01.org.

**Comment by rakuco** [comment]
The change in download.01.org has been done. I've also kept a copy of the files in the previous location while this PR isn't merged so that there's no window where we link to a location that does not exist.

**Comment by halton** [comment]
@baleboy @bspencer please merge if it is lgtm.

**Comment by baleboy** [comment]
LGTM

**Comment by halton** [comment]
@bspencer could you merge this PR and update the website? @rakuco has made the change on 01.org.

**Pull request merged**
