### PR TITLE
Initial Structure for Chinese Contents

### PR DESCRIPTION
**Pull request by jondong**
In this solution we've duplicate each line of contents with its chinese
translations, and added a new attribute: lang="en" or "zh" to identify
if this content is for English or Chinese. We also created a cookie
"local_lang" to save the choice of the user, this cookie will get loaded
everytime that every page get rendererd, to update the body element
class attribute, and the replacement of this attribute can trigger the
replacement of CSS rule for the element with lang settings, which
controls if this element will be shown or not.

The benefit of this solution is that we can keep the website logic all
together in the same place for both English and Chinese contents, very
easy to maintain. And the cons is as Markdown grammar do not support to
add attributes into element, we have to replace the existing markdown
files with the filetype which support this feature, maybe jade is a best
choice.

BUG=XWALK-6350

### CODE REVIEW

**Comment by jondong** [comment]
@bspencer @chuan9 @shaoboyan PTAL.

**Comment by bspencer** [comment]
The approach to organizing the languages is ok with me.  Before publishing anything that displays to the end user we need to clean up the UI and make it responsive to size (needs to look good at all sizes).  Here's what I see now:  http://imgur.com/YhwH7hi    Let's put the link subtly in the header like the XDK site:  http://www.intel.cn/content/www/cn/zh/architecture-and-technology/realsense-overview.html 

I think we can drop the "getting started" red box in the header on all pages and put this language selection drop-down.   Otherwise there should be no indication of language option on the page.

**Comment by jondong** [comment]
@bspencer Thanks for the review. Yes the UI looks pretty ugly by now, :), and the translation in the main page hasn't completed. I didn't pay much attention on refining the UI but just verify the functionality to see if it works. Do you think if would be better to create a dedicate branch for the Chinese task? or just commit the patches directy into master?

BTW use drop-down for language selection is a good idea, :)

**Comment by jondong** [comment]
@bspencer I'll cloose this PR and submit it again when we reaches something. Thanks for your advice!

**Pull request closed without merging**
