### PR TITLE
ios support

### PR DESCRIPTION
**Pull request by makc**
it says it supports ios8 in the same page

### CODE REVIEW

**Comment by baleboy** [comment]
LGTM. The FAQ needs updating in other places too... @bspencer

**Comment by baleboy** [comment]
I just realized that this change was submitted to the processed HTML. The actual source is /public/documentation/about/faq.md

**Comment by bspencer** [comment]
no worries, I'll take care of it.

**Comment by makc** [comment]
Very well then.

**Comment by rakuco** [comment]
thanks for the contribution anyway!

**Pull request closed without merging**
