### PR TITLE
"Can I Use" page added to APIs section of docs

### PR DESCRIPTION
**Pull request by bspencer**
Data from Halton's documentation on platform support for APIs.
The table is generated from a json file for easier updating, hopefully.
@baleboy @halton  please take a look.

### CODE REVIEW

**Comment by bspencer** [comment]
Closing for now to fix some things.

**Comment by zqzhang** [comment]
Hi @bspencer ,

I like the idea of "Can I Use"! Per the `caniuse.jpg` attached in your MSR, I have some comments below for your reference.

- Since you put this page under [APIs](https://crosswalk-project.org/documentation/apis.html), paralleling with the [Web APIs](https://crosswalk-project.org/documentation/apis/web_apis.html), why not list all the features listed in the [Web APIs] page?
- The [Can I Use] page organizes APIs as `Web APIs` and `Experimental APIs` which are both partially included in the [Web APIs](https://crosswalk-project.org/documentation/apis/web_apis.html) page. That means it uses a different categorizing method from the [APIs] page.
- I think it is better list all features that listed in the [Web APIs] and [Embedding API] in the [Can I Use] page, and use the same categories. And if a feature is listed in the [Can I Use] page, it shall be described in the [Web APIs] or [Embedding API] page.

Thanks,
Zhiqiang

**Comment by bspencer** [comment]
Agree on the proposal for keeping the same level of API detail as the other section, and perhaps even merge it into the Web API page... not sure.  What we'll need is an owner to keep each API status updated each month or at least each release.

**Comment by zqzhang** [comment]
> What we'll need is an owner to keep each API status updated each month or at least each release.

How about once or twice per milestone (generally 6 weeks)? ONCE means that update the APIs at the end of the milestone, for example, a new branch setup. TWICE means that one more update after the rebase to upstream Chromium which shall introduces new features.

I guess 'each release' is the same as 'once per milestone', not the Crosswalk canary release, right?

**Pull request closed without merging**
