### PR TITLE
Use static Markdown for the Downloads page in Chinese.

### PR DESCRIPTION
**Pull request by chuan9**
Change https://crosswalk-project.org/documentation/downloads_zh.php to a static page. 
It is a chinese version of https://crosswalk-project.org/documentation/downloads.html.
BUG=XWALK-7287

### CODE REVIEW

**Comment by chuan9** [comment]
@jondong Please have a review. Thanks

**Comment by baleboy** [comment]
LGTM

**Comment by baleboy** [comment]
I'll go ahead and merge this as I would like to remove the php script from the site. If further changes are needed they can be taken in a follow-up PR.

**Comment by chuan9** [comment]
ok， thanks!

**Pull request merged**
