### PR TITLE
Announce Crosswalk 15 Beta

### PR DESCRIPTION
**Pull request by baleboy**
SSIA

### CODE REVIEW

**Comment by baleboy** [comment]
@bspencer PTAL

**Comment by bspencer** [comment]
Nice announcement.

**Comment by bspencer** [comment]
@baleboy,  Should I wait for  LGTM from @lincsoon @funjunwei or @halton before I publish live?

**Comment by halton** [comment]
This PR have LGTM from me.

**Comment by fujunwei** [comment]
LGTM.

**Comment by lincsoon** [comment]
LGTM

**Pull request merged**
