### PR TITLE
Update the windows build dependency according to latest Chromium Guide

### PR DESCRIPTION
**Pull request by Shao-Feng**
Update the windows build dependency according to latest Chromium Guide https://chromium.googlesource.com/chromium/src/+/master/docs/windows_build_instructions.md

### CODE REVIEW

**Comment by rakuco** [comment]
+ @darktears

**Comment by rakuco** [comment]
I think there's room for more improvements:
* This is Markdown, so you can just use

    ```
    1. item
    1. other item
    ```
   without having to worry about their numbering.
* You could explain that our Visual Studio dependencies follow Chromium's, so for Crosswalk < 21 we require VS2013, and for Crosswalk >= 21 we need VS2015 Update 2.
* You're mentioning Visual Studio again in item 4. It's better to group everything in a single item.
* Your item 3 looks confusing. It's better to say "We test and support 64-bit Windows builds on Windows 7 or later. 32-bit builds may work, but are unsupported."

**Comment by Shao-Feng** [comment]
Thanks to Raphael's comment. The file is updated

**Comment by rakuco** [comment]
lgtm

**Pull request merged**
