### PR TITLE
[Windows] Document Visual Studio support.

### PR DESCRIPTION
**Pull request by darktears**

### CODE REVIEW

**Comment by darktears** [comment]
We should include the two images there : https://github.com/otcshare/crosswalk-internal/wiki/Hacking-Crosswalk-Chromium-on-Windows#run-and-debug-inside-visual-studio

**Comment by bspencer** [comment]
Where do you want the new visual studio page in the navigation?  I didn't see any addition to the _data.json file.  Like this: 
...
  "building_crosswalk": {
    "title": "Building Crosswalk"
  },
  "visual_studio": {
     "title": "Building using Visual Studio"
 },
  "contributing-code": {
    "title": "Contributing code"
  },
...
Also, the link to the images gives me "404, page not found."  Perhaps I don't have the right permissions.

**Comment by darktears** [comment]
@bspencer Fixed. I can send you the images and where to integrate them.

**Comment by darktears** [comment]
maybe I can try to add them

**Comment by darktears** [comment]
@bspencer please review

**Pull request merged**
